---
version: '1.0'
services:
  dashboard:
    container_name: next_dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports: [3001:3000]
    networks: [next_dashboard]
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks: [next_dashboard]
networks:
  next_dashboard:
    driver: bridge
